sigBeatIn.fd = 15;
sigBeatIn.fc = 735;
sigBeatIn.phic = 0;
sigBeatIn.phid = pi/4;
sigBeatIn.t1 = 0;
sigBeatIn.t2 = 2.2;
sigBeatIn.fs = 8000;
sigBeatIn.Amp = 10;
sigBeatSum = sum2BeatStruct(sigBeatIn);
figure(1);
plot(sigBeatSum.times,sigBeatSum.values);
xlabel('Time (s)'); ylabel('x(t)');
title('Signal from t = 0s to t = 2.2s (Entire Duration)');
figure(2);
plot(sigBeatSum.times(100:700),sigBeatSum.values(100:700));
xlabel('Time (s)'); ylabel('x(t)');
title('Signal for Short Duration');
